### ISSUE TITLE
MESH created with ezdxf can be read with edrawings but not freeCAD or Autodesk

### ISSUE THREAD

**Issue by omrivolk** [mozman/ezdxf#1219]
Here is my code:

```Python
import ezdxf
import numpy as np

x,y = np.meshgrid(range(-3,3),range(-3,3))
z = x**2 + y**2

doc = ezdxf.new('R2010', setup=True)

# Add a mesh entity
msp = doc.modelspace()

rows, cols = z.shape

# Add a MESH entity
mesh = msp.add_mesh()

msp.doc.layers.add("3d_surface")
mesh = msp.add_mesh(dxfattribs={"layer": "3d_surface"})

with mesh.edit_data() as mesh_data:
    # Create vertices from X, Y, and dem_data (Z)
    for i in range(rows):
        for j in range(cols):
            mesh_data.vertices.append((x[i, j], y[i, j], z[i, j]))

    # Create faces (each grid cell becomes a quadrilateral face)
    for i in range(rows - 1):
        for j in range(cols - 1):
            # Vertex indices for the four corners of the grid cell
            v0 = i * cols + j          # Top-left
            v1 = v0 + 1                # Top-right
            v2 = v0 + cols             # Bottom-left
            v3 = v2 + 1                # Bottom-right

            # Add a quadrilateral face
            mesh_data.faces.append((v0, v1, v3, v2))
    
dxf_file_path = 'example.dxf'
doc.saveas(dxf_file_path)
```

The created file can be read correctly by edrawings and on sharecad.org but not by freecad or autodesk. 

Autodesk viewer gives the following:

> AutoCAD-InvalidFile Sorry, the drawing file is invalid and cannot be viewed. - Please try to recover the file in AutoCAD, and upload it again to view.
> 
> TranslationWorker-InternalFailure Unrecoverable exit code from extractor: -1073741831
> 

Am I doing something wrong?

**Comment by mozman** [comment]
The issue was caused by an empty MESH entity here:
```Python
# Add a MESH entity
mesh = msp.add_mesh()
```

This mesh has no vertices or faces and such empty `MESH` entities are invalid for AutoCAD and BricsCAD.
I am not sure if this restriction is new or has always existed. The next version of `ezdxf` will not export empty meshes and the auditor will destroy such meshes.

**Comment by omrivolk** [comment]
Amazing, thanks. I was struggling with this for hours. Both ChatGPT and Gemini couldn't figure it out!

**Comment by omrivolk** [comment]
Amazing, thanks. I was struggling with this for hours. Both ChatGPT and Gemini couldn't figure it out!

**Comment by mozman** [comment]
The problem with AI is the lack of understanding and hype of the developers of these models because they have to impress their investors and these investors have the same or less programming knowledge as the AI ​​models themselves. Don't expect miracles, these are just statistical language models, no matter what OpenAI, Anthropic or Microsoft say.
