### ISSUE TITLE
Question - Color Saturation / Brightness in Realistic View

### ISSUE THREAD

**Issue by ZL-Xiao** [mozman/ezdxf#124]
I got a problem about color after updating to v0.11.

2D Wireframe View is fine (unchanged), but the Realistic View is changed.

v0.9
![1](https://user-images.githubusercontent.com/49629843/75639952-0e0b4900-5c6e-11ea-8f84-37acf0b4f6e5.jpg)

v0.11
![2](https://user-images.githubusercontent.com/49629843/75639986-2b401780-5c6e-11ea-8546-191c05c6fd43.jpg)

The code didn't changed, but the color is more... grey?

I'm guessing it's something about lighting or the 'SUN' object? But can't find the solution in the documentation.

Any idea/tips to solve this?

Thank you for your time.

**Comment by mozman** [comment]
This topic is not very well documented in the DXF reference, so most information is just guessing:

Display rendering settings are set in the VPORT entity:

```Python
# set *Active viewport
# vport = doc.viewports['*Active'][0]
# or simpler
vport = doc.set_modelspace_vport(height=3, center=(0, 0))

# set render modes
# 0 = 2D Optimized (classic 2D)
# 1 = Wireframe
# 2 = Hidden line
# 3 = Flat shaded
# 4 = Gouraud shaded
# 5 = Flat shaded with wireframe
# 6 = Gouraud shaded with wireframe
vport.dxf.render_mode = 5
```
Or use visual styles:

Setup visual styles at `new()`:
```Python
doc = ezdxf.new(setup=['visualstyles'])  # or setup=True to setup everything
vport = doc.set_modelspace_vport(height=3, center=(0, 0))

# available visual styles:
# 2dWireframe
# Basic
# Brighten
# ColorChange
# Conceptual
# Dim
# EdgeColorOff
# Facepattern
# Flat
# FlatWithEdges
# Gouraud
# GouraudWithEdges
# Hidden
# JitterOff
# Linepattern
# Modeling
# OverhangOff
# Realistic
# Shaded
# Shaded with edges
# Shades of Gray
# Sketchy
# Thicken
# Wireframe
# X-Ray

styles = doc.rootdict['ACAD_VISUALSTYLE']
vport.dxf.visual_style_handle = styles['Sketchy'].dxf.handle

```
Some of this styles are just 'internal' styles, which means they do not show up in selection boxes in CAD applications. And I don't know how `render_mode` and `visual_style_handle` interact. Also the styles seem not to work properly, although I extracted them from ACAD files, maybe some information is missing. I have no plans to improve usability of this topic because I don't care.

To be clear, DXF is not the right tool to setup rendering scenes and visual styles, it is more about the geometry and data exchange.

**Comment by ZL-Xiao** [comment]
Got it!

Thank you for your time, and thanks for this package, really really helps me a lot.
