### ISSUE TITLE
generated dxf file with text entity can not be opened by Autodesk Viewer

### ISSUE THREAD

**Issue by zulliu** [mozman/ezdxf#127]
Hi, I was trying to generate a dxf file with text entity and found it can not be processed by Autodesk online viewer with "Processing failed".  So I tried to run /examples/entities/text.py and
the simple example on READ.md, the generated file text_alignment.dxf and test.dxf  are having the same issue with Autodesk online viewer. It also can not be recognized by Truviewer 2020. 
I was using python 3.6 and ezdxf 0.11.1

**Comment by mozman** [comment]
Hi!

You have to be precise the term "can not be opened" means the application stops with an error message, which is not the problem here, the application just do not show the entities, because the viewport is not centered at the text entities, you have to zoom to "extends":
![zoom_to_extends](https://user-images.githubusercontent.com/4230966/76046424-2aee9780-5f60-11ea-8654-5701b33f7501.png)

Which shows you the text:
![text](https://user-images.githubusercontent.com/4230966/76046636-b700bf00-5f60-11ea-8335-e62056926eab.png)

I added this line to the example `text.py`  to locate the viewport at the text entities:

    doc.set_modelspace_vport(height=30, center=(15, 0))

**Comment by zulliu** [comment]
Thank you so much for your detailed explanation. My problem was solved.
