### ISSUE TITLE
Problem creating viewports

### ISSUE THREAD

**Issue by th555** [mozman/ezdxf#18]
It seems when adding viewports to the paper space, the first time it's not actually created. When added a second time it works correctly.
No viewport created:
```
import ezdxf

dxf = ezdxf.new('R12')
model = dxf.modelspace()
paper = dxf.layout()
model.add_polyline2d([(0, 0), (10, 10), (2, 7), (0, 0)])
paper.add_viewport(center=(105,145), size=(200,280), view_center_point=(0,0), view_height=22)
dxf.saveas('viewport.dxf')
```
Viewport correctly created:
```
import ezdxf

dxf = ezdxf.new('R12')
model = dxf.modelspace()
paper = dxf.layout()
model.add_polyline2d([(0, 0), (10, 10), (2, 7), (0, 0)])
paper.add_viewport(center=(105,145), size=(200,280), view_center_point=(0,0), view_height=22)
paper.add_viewport(center=(105,145), size=(200,280), view_center_point=(0,0), view_height=22)
dxf.saveas('viewport.dxf')
```

I'm using ezdxf 0.7.9 in python 2.7 on ubuntu.

**Comment by mozman** [comment]
Hi!

I know that there are some problems with the VIEWPORT entity, because the DXF standard
just describes the VIEWPORT entity, but not how to setup the internal structures of a DXF
file to use the VIEWPORT entity correctly. The only way to figure out how this works is reverse
engineering.

1. I don't have a AutoCAD license now, I just use TrueView, which means I can't create DXF 
   files with VIEWPORT entities with AutoCAD.
2. I have neither the time nor the desire to deal with this problem.

**Comment by thatcadguy** [comment]
@mozman not necessarily volunteering to fix this, but now that you're on GitHub will you consider pull requests?

**Comment by mozman** [comment]
Yes!

**Comment by mozman** [comment]
VIEWPORT support is more advanced in lastest ezdxf versions
