### ISSUE TITLE
Release memory after usage

### ISSUE THREAD

**Issue by elunty** [mozman/ezdxf#19]
So i've noticed that dxf files can use huge amounts of memory compared to their initial file size (ie: 200mb dxf can use up to 5gb of memory).. but i'm wondering if there is a way to free up the memory after we are done reading our data.

What most libraries would do:

**style 1:**
with ezdxf.readfile(...) as dwg:
    do_something(dwg)
#memory is cleared by this line

**style 2:**
dwg = ezdxf.readfile(...)
do_something(dwg)
dwg.close()
#memory is cleared by this line

It seems like none of these options exist for this particular library. Am i missing something obvious? Just having the python program exit is not an option, since my dxf reading is part of a webserver that runs indefinitely.

**Comment by mozman** [comment]
ezdxf keeps no external resources open, therefore a `close()` is not necessary.

The drawing object contains all the DXF management data and the entity database,
if the drawing object goes out of scope the garbage collector removes all the data
from memory (it's Python). If the drawing object doesn't go out scope, use: `del dwg`

**Comment by elunty** [comment]
Fair enough. Do you think that amount of memory usage seems reasonable, or am i doing something horribly wrong?

**Comment by mozman** [comment]
ezdxf keeps the whole DXF content in memory as lists of tuples.

On my 64-bit machine a tuple needs 64 bytes + 28 bytes for an int + 49+length bytes for the string.

So, yes ezdxf needs much memory - and this will not change, because this is the fundamental
design of ezdxf to keep all data in memory and preserving ALL data of the DXF file.

If just want to read DXF files: my dxfgrabber package has a smaller memory footprint.

https://github.com/mozman/dxfgrabber

**Comment by elunty** [comment]
Sure, I'll give it a try, thanks. Didn't know you were that author of both.

**Comment by mozman** [comment]
Btw: a 200MB file is also no fun in AutoCAD or any CAD application - I know it, because CAD is my regular job.
