### ISSUE TITLE
MTEXT dxf attrib for inital text group code

### ISSUE THREAD

**Issue by hjkatz** [mozman/ezdxf#2]
Mozman,

First off, fantastic library, you rock. Also, I'm back to working on DXF stuff so I'll be around and hopefully able to help add some features as I come across them.

Second, the MTEXT entity type is defined in a DXF to use group codes 1 as the initial 250 chars of text and then 3 as the additional as many as needed. Currently there is no way to query on either group code due to the definition in modern/mtext.py

Would it be possible to add at minimum group code 1 so we could use some filtering?

Then in the future perhaps there might be a way to allow for dxf attribs that span multiple group codes?

Thoughts?

--Harrison

**Comment by mozman** [comment]
Hi!

Help is very appreciated, espacially if you have deeper knowledge of the DXF format, because the 
DXF reference describes all the entites, but provides very little information on how entities are oganized 
in the DXF file (OBJECTS section!).

The MText class (ezdxf.modern.mtext.MText), manages the the splitting of larger text chunks into group 
codes (1) and (3) by itself, the user do not need to know anything about this features (ezdxf should be 
_easy DXF_). 

Interface for getting/setting text: get_text()/set_text()

But it is possible to dive deeper into the DXF tags:

- tags are organized in the ClassifiedTags() class
  ezdxf.lldxf.classifiedtags.ClassifiedTags()
  lldxf stands for _low level dxf_
- access tags of an entity by entity.tags
- tags are namedtuples ezdxf.lldxf.types.DXFTag()

Messing around with tags:

1. get the tag subclass: entity.tags.get_subclass('AcDbMText')
2. you get an ezdxf.lldxf.tags.Tags() class, which  is an extended Python list, containing DXFTag() objects.
3. for processing tags look at get/set_text() in MText
4. as long as you manipulate the tags according to the  DXF standard, ezdxf is fine with your changes.
       
Attention! 
Points are special: DXFTag(x-group-code, (x, y[,z])), where x-group-code is the group code of the x coordinate (10, 110, ...)

Thanks for your contribution in advance!

Manfred
