### ISSUE TITLE
Autoscaling of the output image in DXF > PNG conversion

### ISSUE THREAD

**Issue by nancylee713** [mozman/ezdxf#220]
Hello, I am working on converting a DXF file to PNG format, using one of the [add-ons](https://ezdxf.readthedocs.io/en/stable/addons/draw.html#draw) tool in `ezdxf`.
Below is the script that I ran to output an image file.

```
import matplotlib.pyplot as plt
import ezdxf
from ezdxf.addons.drawing import RenderContext, Frontend
from ezdxf.addons.drawing.matplotlib_backend import MatplotlibBackend

doc = ezdxf.readfile('./test.dxf')
msp = doc.modelspace()

fig = plt.figure()
ax = fig.add_axes([0, 0, 0, 0])
ax.set_aspect('auto')
ax.set_axis_off()
ctx = RenderContext(doc)
out = MatplotlibBackend(ax)
Frontend(ctx, out).draw_layout(msp, finalize=True)
fig.savefig('png_dxf.png', dpi=300)
```

The resulting file did contain a DXF content but it wasn't scaled to the desired aspect ratio of the DXF (please see the second screenshot image below). For some reason, the output image also ignored the bottom right sections.

I played around with different axis values or autoscaling part in `finalize=True` option in the code, but still not getting the desired output. Which part of the script needs to change to solve the scaling issue? I really appreciate your help. 

**Actual output**
![png_dxf_actual](https://user-images.githubusercontent.com/24424825/91422633-65434c80-e892-11ea-8ffc-326d940b31a8.png)

**Desired output**
![png_dxf_desired](https://user-images.githubusercontent.com/24424825/91422643-67a5a680-e892-11ea-8202-3ac921b989e5.png)

**Comment by mbway** [comment]
The aspect ratio looks fine, nothing is stretched, but the cropping looks wrong.

I see a few things wrong. Firstly, the axis should be created with:
```python
ax = fig.add_axes([0, 0, 1, 1])
```
passing all zeros should have made the axis have no width or height, so I'm not sure why there is any output in your resulting image.

secondly, the lines
```python
ax.set_aspect('auto')
ax.set_axis_off()
```
should be removed. The aspect ratio will already be set to equal by the matplotlib backend, and selecting auto would result in undesirable stretching anyway. `set_axis_off` causes issues with setting the face color so the backend will automatically make the axis invisible without using `set_axis_off` (see the `MatplotlibBackend` constructor)

With many CAD files I have encountered, there is additional 'junk' which can be very far away from the main content of the file. CAD applications appear to be unfazed by this (maybe they store the current view so when the file is loaded the view is restored rather than fitting in the content of the entire file?).
one way to check for this junk would be to try drawing with the PyQtBackend with `debug_draw_rect=True`. This will draw a rectangle around the content of the CAD file. If the rectangle appears much larger than the content, then the CAD file has extra entities around the edge that you don't want.

How you go about removing this is up to you, or if you prefer to draw the entire file but zoom in on a portion of it, just set the axis limits before saving (I obtained the coordinates using the `examples/addons/drawing/cad_viewer.py` which prints the coordinates of the mouse cursor, but you could probably also use a CAD application):
```python
import matplotlib.pyplot as plt
import ezdxf
from ezdxf.addons.drawing import RenderContext, Frontend
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend
import os

doc = ezdxf.readfile('../examples_dxf/text.dxf')
layout = doc.modelspace()

fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
ctx = RenderContext(doc)
out = MatplotlibBackend(ax)
Frontend(ctx, out).draw_layout(layout, finalize=True)

fig.savefig('out.png', dpi=300)
ax.set_xlim((1920, 3200))
ax.set_ylim((1200, 1900))
fig.savefig('out_cropped.png', dpi=300)
```
out.png:
![out](https://user-images.githubusercontent.com/4923501/91439827-90fc0d80-e865-11ea-978c-86eaa2f5fd93.png)
out_cropped.png:
![out_cropped](https://user-images.githubusercontent.com/4923501/91439848-96f1ee80-e865-11ea-895c-aaa71c50c801.png)

**Comment by nancylee713** [comment]
Thank you for the detailed explanations and the example above!

With `cad_viewer` script, I was able to obtain the coordinates to specify the axis limits and got this result below, which is much closer to the desired output. Thanks for your help!

![out_cropped](https://user-images.githubusercontent.com/24424825/91505822-8431f500-e90b-11ea-84ae-390923cf96d0.png)

**Comment by saeryounglee** [comment]
Hi again!

I have a follow-up question regarding the line thickness of the output image.
The goal is to render the image as similarly as shown in the cad viewer, and I have tried the three approaches so far:

```
doc = recover.readfile(filename)
msp = doc.modelspace()
```

**Approach 1**
```
doc.set_raster_variables(units='mm')
```

**Approach 2**
```
for e in msp:
    e.dxf.lineweight = 1
```

**Approach 3**
```    
matplotlib.qsave(
            doc.modelspace(), 'out.png', bg="#FFFFFF00", dpi=300)
```

Combining approach 1 and 2 render the best result:
<img width="46" alt="Screen Shot 2020-09-22 at 7 22 09 PM" src="https://user-images.githubusercontent.com/62236641/93871064-06de8200-fd09-11ea-80a4-4fe353bff55f.png">

While approach 3 renders thicker lines:
<img width="100" alt="Screen Shot 2020-09-22 at 7 22 40 PM" src="https://user-images.githubusercontent.com/62236641/93871070-0940dc00-fd09-11ea-8584-73b8f8bacd6f.png">

Is there a way to further improve the resolution of the image in ezdxf?
<img width="186" alt="Screen Shot 2020-09-22 at 7 21 52 PM" src="https://user-images.githubusercontent.com/62236641/93871076-0d6cf980-fd09-11ea-810c-89bc3e6f5f1d.png">

**Comment by nancylee713** [comment]
Hi again!

I have a follow-up question regarding the line thickness of the output image.
The goal is to render the image as similarly as shown in the cad viewer, and I have tried the three approaches so far:

```
doc = recover.readfile(filename)
msp = doc.modelspace()
```

**Approach 1**
```
doc.set_raster_variables(units='mm')
```

**Approach 2**
```
for e in msp:
    e.dxf.lineweight = 1
```

**Approach 3**
```    
matplotlib.qsave(
            doc.modelspace(), 'out.png', bg="#FFFFFF00", dpi=300)
```

Combining approach 1 and 2 render the best result:
<img width="46" alt="Screen Shot 2020-09-22 at 7 22 09 PM" src="https://user-images.githubusercontent.com/62236641/93871064-06de8200-fd09-11ea-80a4-4fe353bff55f.png">

While approach 3 renders thicker lines:
<img width="100" alt="Screen Shot 2020-09-22 at 7 22 40 PM" src="https://user-images.githubusercontent.com/62236641/93871070-0940dc00-fd09-11ea-8584-73b8f8bacd6f.png">

Is there a way to further improve the resolution of the image in ezdxf?
<img width="186" alt="Screen Shot 2020-09-22 at 7 21 52 PM" src="https://user-images.githubusercontent.com/62236641/93871076-0d6cf980-fd09-11ea-810c-89bc3e6f5f1d.png">

**Comment by mbway** [comment]
the resolution will be linked to the dpi, a higher number should increase the output image size. Maybe combine that with setting the line weights?

**Comment by nancylee713** [comment]
Thank you so much for taking the time to reply! I'll experiment with lineweight settings to see if I can get it working this way.

**Comment by mozman** [comment]
Added an additional option for lineweight scaling to `matplotlib.qsave()` v0.15a1, see also #238. Set `lineweight_scaling` to 0 to disable lineweights at all and all lines should be drawn with a min lineweight of 1 pixel.

**Comment by saeryounglee** [comment]
Woah! the resulting image looks a lot better in terms of resolution. Thank you for adding this feature!

**Comment by DominikFilipiak** [comment]
In case you are struggling with too thick lines just as me - please remember to set the correct DPI in these two places:
```py
fig = plt.figure(dpi=1000)
...
fig.savefig('out_cropped.png', dpi=1000)
```
Doing it only with `savefig` was not enough in my case.
