### ISSUE TITLE
Matplotlib font properties

### ISSUE THREAD

**Issue by nancylee713** [mozman/ezdxf#241]
Hi again!

In dxf-to-png conversion, I ran into a text rendering issues for DXF files containing CJK (Chinese, Japanese, Korean) 
characters. 

For instance, I have a `simple_text.dxf` containing Korean characters, which is visualized with `cad_viewer.py` with no problem:
<img width="1595" alt="simpletest_cadviewer" src="https://user-images.githubusercontent.com/24424825/94133541-bfd4c600-fe9b-11ea-9ad3-ec85eb13f2c4.png">

When the DXF file is rasterized with dxf2png tool, the output image displays Korean characters as squares:
<img width="1387" alt="initial" src="https://user-images.githubusercontent.com/24424825/94133722-ff031700-fe9b-11ea-8d34-e414a300eb84.png">

When I added a new Korean font (i.e., `NanumBarunGothic.otf`) by specifying its filename to `FontProperties` and passed it to the backend params, the characters are displayed properly.
```
... (omitted for brevity)
from matplotlib.font_manager import FontProperties

myfont = FontProperties(fname='/Library/Fonts/NanumBarunGothic.otf', size=15)

doc = ezdxf.readfile('./simple_text.dxf')
msp = doc.modelspace()
fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
ctx = RenderContext(doc)
ctx.set_current_layout(msp)
out = MatplotlibBackend(ax, font=myfont)
Frontend(ctx, out).draw_layout(msp, finalize=True)
fig.savefig('simple_text.png', dpi=300, transparent=True)
plt.close(fig)
```

<img width="1394" alt="fontadded" src="https://user-images.githubusercontent.com/24424825/94133939-4c7f8400-fe9c-11ea-91ee-6c069f7f197f.png">

However, there were some cases in which the following error message was returned:
```
    Frontend(ctx, out).draw_layout(msp, finalize=True)
  File "/usr/local/lib/python3.8/dist-packages/ezdxf/addons/drawing/frontend.py", line 93, in draw_layout
    self.draw_entities(reorder.ascending(layout, handle_mapping))
  File "/usr/local/lib/python3.8/dist-packages/ezdxf/addons/drawing/frontend.py", line 113, in draw_entities
    self.draw_entity(entity, properties)
  File "/usr/local/lib/python3.8/dist-packages/ezdxf/addons/drawing/frontend.py", line 133, in draw_entity
    self.draw_text_entity_2d(entity, properties)
  File "/usr/local/lib/python3.8/dist-packages/ezdxf/addons/drawing/frontend.py", line 180, in draw_text_entity_2d
    for line, transform, cap_height in simplified_text_chunks(
  File "/usr/local/lib/python3.8/dist-packages/ezdxf/addons/drawing/text.py", line 279, in simplified_text_chunks
    font_measurements = out.get_font_measurements(cap_height, font=font)
  File "/usr/local/lib/python3.8/dist-packages/ezdxf/addons/drawing/matplotlib.py", line 186, in get_font_measurements
    return self._text.font_measurements.scale_from_baseline(
  File "/usr/local/lib/python3.8/dist-packages/ezdxf/addons/drawing/text.py", line 75, in scale_from_baseline
    assert math.isclose(self.baseline, 0.0)
```

I'm not sure if this error stems from the font measurements of a particular font or something else. From the error message, I might infer that there is a problem with the baseline of the font not being 0? I appreciate your explanations.

**Comment by mbway** [comment]
there is a baked in assumption that the baseline of the font is always at y=0 since I haven't encountered a font where that wasn't the case. I had a quick look at the text layout algorithm and there might be a few bugs with fonts where the baseline isn't at y=0 such as the calculation of `line_ys` in text.py.

Also I haven't thought about what to do if the font doesn't contain the glyphs for 'X', 'x' and 'p' since those are used to measure the font. I tried rendering some ascii text with the NanumBarunGothic font and it looks like this font at least has glyphs for Xxp, but maybe not all fonts would have? I think the only way to support a completely non-ascii font would be to pass in FontMetrics manually or use a proper text library like freetype to do the measurements. But since this is just an addon it wouldn't make much sense to pull in another dependency just for this case.

To support this font is just a matter of fixing support for baselines other than 0. I'll try to look into that when I have the time. It might require modifying an existing font ttf to shift the characters up and verify that the output is the same.

```python
import matplotlib.pyplot as plt
from matplotlib.font_manager import FontProperties
from ezdxf.addons.drawing.matplotlib import TextRenderer

fig, ax = plt.subplots()
font = FontProperties(fname='NanumBarunGothic.otf')
r = TextRenderer(font, False)
print(r.font_measurements.__dict__.items())
fig.tight_layout()
ax.set_aspect('equal', 'datalim')
ax.set_axis_off()
ax.text(0, 0, 'Xxp 여보세요', fontproperties=font)
ax.autoscale()
fig.savefig('/tmp/text.png')
```
prints
```
dict_items([('baseline', -0.035937500000000004), ('cap_top', 0.7209375), ('x_top', 0.51), ('bottom', -0.2809375)])
```
in this case since the baseline is so close to 0 anyway you could just manually set it to 0 as a temporary fix?

**Comment by nancylee713** [comment]
Thanks again for your kind and quick response!

To get around the baseline issue, I decided to use Noto Sans CJK to support non-ascii fonts. 

After installing the font with `apt-get install -y fonts-noto-cjk` and adding this font to font properties, everything works fine!

```
myfont = FontProperties(
      fname='/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc') 
```
