### ISSUE TITLE
MLEADER crash

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#295]
for me, trying to draw the MLEADER file with qsave gives
```
skipped entity MULTILEADER(#403). Reason: "Unsupported entity"
...
```
and loading in the cad viewer gives
```
C-Extension: False
drawing Model
Traceback (most recent call last):
  File "./examples/addons/drawing/cad_viewer.py", line 233, in _select_doc
    self.set_document(doc, auditor)
  File "./examples/addons/drawing/cad_viewer.py", line 257, in set_document
    self.draw_layout('Model')
  File "./examples/addons/drawing/cad_viewer.py", line 292, in draw_layout
    Frontend(self._render_context, self._backend).draw_layout(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 138, in draw_layout
    self.draw_entities(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 156, in draw_entities
    self.draw_entity(entity, properties)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 177, in draw_entity
    self.draw_proxy_graphic(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 451, in draw_proxy_graphic
    self.draw_entities(gfx.virtual_entities())
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 144, in draw_entities
    for entity in entities:
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/proxygraphic.py", line 158, in virtual_entities
    result = method(self._buffer[index + 8: index + size])
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/proxygraphic.py", line 258, in circular_arc
    arc_type = bs.read_struct('L')[0]
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/tools/binarydata.py", line 59, in read_struct
    result = struct.unpack_from(fmt, self.buffer, offset=self.index)
struct.error: unpack_from requires a buffer of at least 8 bytes
Aborted (core dumped)
```

I'm on the latest commit: 1fe629df19dae31bd58e7e43fd2a8394130878f1

I haven't looked into this much though. Are there modifications that haven't been committed yet to achieve the cad_viewer screenshot here: https://github.com/mozman/ezdxf/discussions/264#discussioncomment-190761

(I know that 'full support' for drawing MLEADER is scheduled for 0.16)

**Comment by mozman** [comment]
cad_viewer.py still works on Windows:
![image](https://user-images.githubusercontent.com/4230966/103975775-48d6eb00-5175-11eb-8984-c05145340cb4.png)

In the debugging session(break point at line 258 in proxygraphic.py) for this example file, every time the buffer has 92 bytes the reading index is at 88, reading the `arc_type` expects a long (4 bytes - OD-Spec-DWG p. 271) and the buffer has 4 bytes left, works on Windows - core dump on Linux -- requires 8 bytes buffer for reading 4 bytes data??? The struct param 'L' reads a 4 byte unsigned long according to the Python docs.

Quick fix: `arc_type` is the last attribute and ignored yet, so it is possible to comment out the line 258.

Fixing the `ByteStream()` class for Linux:
1. Adding null bytes to align the buffer length to 8 bytes (92 -> 96)
2. Adding always 8 null bytes to be safe -- because I don't know if this is only an alignment issue

Pleas test something your System:
```Python
import struct

s = b'\07\0\0\0\0\0\0\0'
buffer = memoryview(s)
print(f"Works with {len(s)} byte buffer:")
print(struct.unpack_from('<L', buffer, offset=0)[0])

s = b'\07\0\0\0'
buffer = memoryview(s)
print(f"Works with {len(s)} byte buffer:")
print(struct.unpack_from('<L', buffer, offset=0)[0])

s = b'\0\0\0\0\07\0\0\0'
buffer = memoryview(s)
# Is Buffer alignment to 8 bytes enough?
print(f"Works with {len(s)} byte buffer and 4 byte offset:")
print(struct.unpack_from('<L', buffer, offset=4)[0])

s = b'\0\0\0\0\07\0\0\0\0\0\0\0'
buffer = memoryview(s)
# Always adding 4 or better 8 bytes is required?
print(f"Works with {len(s)} byte buffer and 4 byte offset:")
print(struct.unpack_from('<L', buffer, offset=4)[0])

```

This works on Windows:

![image](https://user-images.githubusercontent.com/4230966/103978765-868b4200-517c-11eb-9837-11c5e0893f48.png)

And on WSL2/Ubuntu:
![image](https://user-images.githubusercontent.com/4230966/103978818-ab7fb500-517c-11eb-8994-47e6af9bbbf9.png)

**Comment by mozman** [comment]
Another test which reflects the problematic situation better:
```Python
s = b'\0\0\0\0\0\0\0\0\07\0\0\0'
buffer = memoryview(s)
print(f"Works with {len(s)} byte buffer and 8 byte offset:")
print(struct.unpack_from('<L', buffer, offset=8)[0])
```

**Comment by mbway** [comment]
I ran the test code and it didn't crash:
```
Works with 8 byte buffer:
7
Works with 4 byte buffer:
7
Works with 8 byte buffer and 4 byte offset:
7
Works with 12 byte buffer and 4 byte offset:
7
Works with 12 byte buffer and 8 byte offset:
7
```
I checked in a debugger and when the cad_viewer crash occurs the buffer is indeed `0, 0, 0, 0` at the point where `struct.unpack_from('L', buffer)` is called. Running `struct.calcsize('L')` on my machine returns `8`

I think the issue is that the format specifiers should always have an explicit endian prefix, otherwise the size is the 'native' size. If you always specify little endian with `<L` then the 'standard size' is used ([source](https://docs.python.org/3/library/struct.html#byte-order-size-and-alignment)):
```
>>> import struct
>>> struct.calcsize('L')
8
>>> struct.calcsize('<L')
4
>>> buffer = b'\x00\x00\x00\x00'
>>> struct.unpack_from('L', buffer)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
struct.error: unpack_from requires a buffer of at least 8 bytes
>>> struct.unpack_from('<L', buffer)
(0,)
```

**Comment by mozman** [comment]
Hi!

Replaced the `read_struct()` by `read_long()` which always uses `'<L'` -- I assume this fixes the issue.

**Comment by mbway** [comment]
yes, adding `<` prevents the crash
