### ISSUE TITLE
questions about speed

### ISSUE THREAD

**Issue by mirlip** [mozman/ezdxf#3]
Hi,
First of all, really great lib, it's a very big help for me :)
Big files can take a lot of time to open, even on a 4.2Ghz I7. Would it be possible to use Numpy or another solution to somehow speedup the read process?
I use DXFGrabber many times a week, it saved my day many times.
Regards

**Comment by mozman** [comment]
ezdxf is heavy I/O bound, no matrix or vector operations, just reading much data and building data structures in memory.

Most potential for optimization is to reduce the cost of function call overhead, which can be done by compiling the code by Cython, which I have done for dxfgrabber. But I removed it later, because the maintenance effort was to high (binary wheels for 32/64 bit Windows/Linux, can't support mac by myself)
and the speed gain to low (2x faster isn't much).

If you can use PYPY, it optimizes function call without any additional work.

Manfred

**Comment by mirlip** [comment]
Hi,
Thank you for the quick answer, I understand. Could you provide a small guide or a link on how to use Cython or pypy? I use your lib in Blender which has CPython 3.5.2, but it can load compiled dlls.

**Comment by mozman** [comment]
For Blender [pypy](http://www.pypy.org/) is no option.

If you are an experienced developer and setup a proper environment to compile C extensions, for the python interpreter used by blender (has to match Python version like 3.5 and bit size  32/64 bit), you can try to use an old version of dxfgrabber (<0.7.5), in version 0.8.0 and later the Cython extension is removed.

If you are not an experienced developer, I think it is not worth the effort to mess around with C extensions, especially on Windows.
