### ISSUE TITLE
Exception drawing hatch

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#302]
When I try to draw the following dxf file it crashes with:
```
Traceback (most recent call last):
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/math/_vector.py", line 557, in __init__
    self.x = v.x
AttributeError: 'tuple' object has no attribute 'x'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matthew/src/ezdxf_upstream/src/load.py", line 16, in <module>
    qsave(doc.modelspace(), '/w/fig.png')
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/matplotlib.py", line 390, in qsave
    Frontend(ctx, out).draw_layout(layout, finalize=True)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 138, in draw_layout
    self.draw_entities(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 156, in draw_entities
    self.draw_entity(entity, properties)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 175, in draw_entity
    draw_method(entity, properties)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 308, in draw_hatch_entity
    polygons = self.nested_polygon_detection(map(to_path, paths))
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/render/nesting.py", line 151, in fast_bbox_detection
    for path in paths
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/render/nesting.py", line 151, in <listcomp>
    for path in paths
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/math/bbox.py", line 98, in __init__
    self.extmin, self.extmax = extends2d(vertices)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/math/bbox.py", line 155, in extends2d
    return Vec2((minx, miny)), Vec2((maxx, maxy))
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/math/_vector.py", line 561, in __init__
    self.x = float(v[0])
TypeError: float() argument must be a string or a number, not 'NoneType'
```
[260C0.dxf.zip](https://github.com/mozman/ezdxf/files/5788340/260C0.dxf.zip)
It should look like this:
![image (44)](https://user-images.githubusercontent.com/4923501/104041697-57eb8680-51d1-11eb-955d-3a0031683ef2.png)

**Comment by mozman** [comment]
Fixed at least the crash.

This HATCH is defined as arc from -180 to 180 and produces an empty path, because I only detect 0 to 360 as full circle.

This problem is not that easy as it seems because the Python modulo rules are problematic -180 % 360 = 180

Shortly I added an `arc_angle_span_deg()` function (which is not used here) and some tests to define the start- end angle variations, and there are a lot:
```Python
    # (start-angle, end-angle, span)
    (0, 0, 0),  # start == end is always 0 by definition
    (360, 360, 0),  # start == end is always 0 by definition
    (-30, -30, 0),  # start == end is always 0 by definition
    (0, 360, 360),  # end angle counter clockwise (ccw) 360 is 360 deg (special)
    (270, 360, 90),  # end angle ccw 360 is 360 deg (special)
    (-90, 360, 90),  # end angle ccw 360 is 360 deg (special)
    (0, -360, 0),  # end angle clockwise (cw) 360 deg is 0
    (90, -360, 270),  # end angle cw 360 deg is 0
    (-90, -360, 90),  # end angle cw 360 deg is 0
    (360, 0, 0),  # start angle 360 is 0
    (360, 90, 90),  # start angle 360 is 0
    (360, -90, 270),  # start angle 360 is 0
    (-360, 0, 0),  # start angle -360 is 0
    (-360, 90, 90),  # start angle -360 is 0
    (-360, -90, 270),  # start angle -360 is 0
    (30, -30, 300),  # crossing 0 deg
    (-30, 30, 60),  # crossing 0 deg
    (180, -180, 0),  # 180 is equal to -180
    (-180, 180, 0),  # 180 is equal to -180
    (90, -90, 180),
    (-90, 90, 180),
    (360, 400, 40),
    (400, 360, 320),
```

I assume to solve this problem is to create a modulo function which preserves the sign (I think modulo in "C" works that way): signed_mod(-90) = -90; signed_mod(-360) = -0?

- (90, 90) should be 0 angle span
- (-270, 90) should be 360
- (0, 360) should be 360 - special treatment because 360 % 360 is 0

I also asked Google and found following information at rosettacode.org:

Normalization  (for this Rosetta Code task)   will keep the same sign, but it will reduce the magnitude to less than a full circle;  in other words, less than 360º.

Normalization   **shouldn't**   change   -45º   to   315º,
An angle of   0º,   +0º,   0.000000,   or   -0º   should be shown as   0º.

And the published code is simple:
```Python
def normalize2deg(a):
    while a < 0: a += 360
    while a >= 360: a -= 360
    return a
```
But doesn't fulfill the requirements ;). -90 => 270, does not preserve the sign!

This works:

```Python
def normalize2deg(a):
    while a <= -360: a += 360
    while a >= 360: a -= 360
    return a
```
But normalization for (270, -270) => (270, -270), doesn't look right!

**Comment by mozman** [comment]
"Solved" the issue by adding another definition:

1. Returns 0 for start angle == end angle by definition
2. Return 360 if normalized angles are equal but start angle != end angle by definition.

**Comment by mozman** [comment]
cad_viewer.py shows the circle for the example file:
![image](https://user-images.githubusercontent.com/4230966/104088557-22de4300-5268-11eb-8b7b-89900a5bd0b1.png)

The backend param `hatch_pattern` has to be 2 to draw the hatch as a solid fill,  else no filling/pattern will be shown. Pattern support of PyQt5 and matplotlib is not very good.
