### ISSUE TITLE
PDF export diverges from CAD application rendering

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#335]
This is a comparison of multi-line text entities in dxf files and pdf files
dxf file:
![image](https://user-images.githubusercontent.com/59160360/106344211-42efa800-62e4-11eb-9a87-8586ded3fa63.png)
pdf file:
![image](https://user-images.githubusercontent.com/59160360/106344248-5438b480-62e4-11eb-8bf2-46c8a17fe6b4.png)
Best wishes

**Comment by mozman** [comment]
We try to improve font rendering, but don't expect pixel perfect results. Ezdxf is not a CAD application and has not the goal to reach the render quality of AutoCAD. The drawing add-on is a nice to have feature, and I like it very much, but it is deliberately an add-on, because it's functionality is not a core goal of ezdxf.

**Comment by mbway** [comment]
I don't know how Chinese fonts are handled so it's very possible that the current font measuring approach fundamentally won't work for non-latin alphabets (it's very basic). The 'proper' approach would be to directly use freetype rather than rely on what matplotlib exposes. For example [this](https://freetype-py.readthedocs.io/en/latest/size_metrics.html). This would also give more control over kerning which could help with https://github.com/mozman/ezdxf/issues/333. I know that ezdxf tries to keep dependencies to a minimum so this may not be an acceptable approach. I think someone more familiar with a non-latin alphabet would be in a better position to implement proper support for other languages. I would be willing to offer support if anyone is interested.

**Comment by mozman** [comment]
The freetype Python bindings rely on a system-wide installed FreeType at runtime. Without getting everything by a simple `pip install ...`, like for matplotlib, it's getting complicated for Windows users. 

The strict "as less dependencies as possible" policy is only valid for the core package. In an add-on like `drawing` you can use it as optional feature to improve rendering, if FreeType is available. But it would be required to start a dedicated page in the documentation to show which dependencies are required for which feature, as already started in the README.md - but better. 

Adding tags (extras_require or so?) to setup.py to install optional packages would be the next consequent step. 

BTW: matplotlib seems to use FreeType internally, but does not expose an interface to the linked version.

**Comment by mbway** [comment]
I think the pypi package bundles freetype:
> From PyPI, recommended: pip install freetype-py. This will install the library with a bundled FreeType binary, so you’re ready to go on Windows, macOS and Linux (all with 32 and 64 bit x86 architecture support).

[source](https://pypi.org/project/freetype-py/)

I know about the matplotlib use of freetype. I did investigate whether it would be possible to use lower level freetype functionality with the matplotlib bundled version but I thought it would be too hacky as a proper solution.

**Comment by mozman** [comment]
I just read the section "Installation with compiling FreeType from source" :-).

OK, you can use it in the `drawing` add-on, and I will look how to add proper support for optional dependencies in setup.py.
