### ISSUE TITLE
How can I build arc based on start point, end point and rotation angle？

### ISSUE THREAD

**Issue by whichen** [mozman/ezdxf#39]
Is there a method to build arc based on start point, end point and rotation angle?
For example, start point(18,-18), end point(18,18), rotation angle(180 degree), can I?

**Comment by DanielPompermayer** [comment]
I'd say we don't have any native method on ezdxf to do so. You'll need to do some calculations there.

**Comment by mozman** [comment]
First, please post such questions at the ezdxf forum:
https://groups.google.com/forum/#!forum/python-ezdxf

I added a helper class ezdxf.algebra.Arc to the develop branch.

reference at: https://ezdxf.mozman.at/docs/algebra/arc.html

usage:

```
import ezdxf
from ezdxf.algebra import Arc

dwg = ezdxf.new('R2010')
msp = dwg.modelspace()

arc = Arc.from_2p_angle(start_point=(18, -18), end_point=(18, 18), angle=180)
msp.add_arc(
    center=arc.center,
    radius=arc.radius,
    start_angle=arc.start_angle,
    end_angle=arc.end_angle,
)

dwg.saveas(r'C:\Users\manfred\Desktop\Outbox\arc.dxf')
```

The arc goes always in counter clockwise orientation from start- to the end point, because 2 points and an angle have two possible arcs as solutions:
![image](https://user-images.githubusercontent.com/4230966/43674346-e532c294-97d2-11e8-95e2-c8ad4405444a.png)

And it works only in 2D, start- and end point have to be in the XY plane (Z-axis is 0).

**Comment by mozman** [comment]
additional feature to avoid unnecessary repetition:
```
arc = Arc.from_2p_angle(start_point=(18, -18), end_point=(18, 18), angle=180)
arc.add_to_layout(msp)
```

**Comment by whichen** [comment]
Thanks a lot for your help.

**Comment by whichen** [comment]
Could you add a parameter to  Arc.from_2p_angle like  Arc.from_2p_angle(start_point=(18, -18), end_point=(18, 18), angle=180 *orientation)
*orientation is optional, by default is counter-clockwise, 1 is for clockwise.

**Comment by mozman** [comment]
As fast solution just swap start- and end point, I will add a 'ccw' parameter, True for counter clockwise direction (default), False for the opposite direction.
