### ISSUE TITLE
Errror when creating layer

### ISSUE THREAD

**Issue by pellegoeg** [mozman/ezdxf#4]
Hi,

Thanks for this great package!

I think I found an error, or I havent found the source of the error, but found a way to provoking the error.

Step by step guide to provoking this error (see the Attached file for code, dxf and screenshot):

1) I use your hatch example on page 18 in [1], "solid_hatch_polyline_path.dxf". I add the line for creating a layer 

`dwg.layers.new('This_Give_Me_And_Error_layer')
`
2) Open the dxf i Autocad Map 2013/2016 or Autocad 2016
3) Save as dwg
4) Create new dwg
5) attach solid_hatch_polyline_path_notworking.dwg file
6) Try to Save, get the recover error.

[ezdxf_error.zip](https://github.com/mozman/ezdxf/files/753209/ezdxf_error.zip)

[1] https://media.readthedocs.org/pdf/ezdxf/latest/ezdxf.pdf

**Comment by mozman** [comment]
Hi!

As I see, the DXF files created by ezdxf can be opened by AutoCAD ( without complain), therefore it seems that ezdxf fullfill all requirements according to the DXF standard, additional requirements of applications like AutoCAD (Map), which are not part of the DXF standard, can not be supported, because I don't know them. 

To be clear: I know there are errors in the objects structures (semantics), but sadly I don't find them, because the file structure is valid, but the DXF semantic is not 100% valid for AutoCAD, but AutoCAD reports no errors.
