### ISSUE TITLE
Floating point precision in vector comparison

### ISSUE THREAD

**Issue by ghemann** [mozman/ezdxf#431]
Not sure if this is by design or intentional but vector comparison (both Vec2 and Vec3, maybe more but only tested these) doesn't compare with double precision, so two points that might be different may be compared as the same

Testing on 0.16.1

`a = ezdxf.acc.vector.Vec2(123.0, 234.354234)`
`b = ezdxf.acc.vector.Vec2(123.0, 234.35423423)`
`print(a == b)` returns True, should be false
`print(a[1] == b[1])` returns False

**Comment by mbway** [comment]
this is the intended behaviour, although it is questionable whether it is the correct approach.
https://github.com/mozman/ezdxf/blob/f7b40e5fbdecdef02d717604a1de371d39823d44/src/ezdxf/math/_vector.py#L346-L356
Different amounts of precision might be required depending on what the units of the document are and the use case.

Also something I noticed when searching the code for this question is that `a == b` should imply `hash(a) == hash(b)` for the hash to be valid, however with the current implementation this is not the case. This can cause incorrect behaviour like:
```python
a = ezdxf.acc.vector.Vec2(123.0, 234.354234)
b = ezdxf.acc.vector.Vec2(123.0, 234.35423423)
print(a == b)  # True
my_set = set([a, b])
print(len(my_set))  # 2
```
the set should not consider `a` and `b` to be different because they are equal

(see [here](https://www.asmeurer.com/blog/posts/what-happens-when-you-mess-with-hashing-in-python/) for more)

**Comment by ghemann** [comment]
Interesting.   What is the rationale for making __eq__ be more a 'near equal' than 'exact equal'?    Are there other member functions that would do an exact equal at full precision? Or is there intent on building this?

**Comment by mozman** [comment]
@ghemann  Comparing floating point values is not easy: https://stackoverflow.com/questions/4915462/how-should-i-do-floating-point-comparison, and comparing vectors in *ezdxf* by `hash(v1) == hash(v2)` uses the full floating point precision.

The implementation of `Vec2/Vec3.__eq__`  in *ezdxf* is not correct, fixing this problems will include:
1. `v1 == v2` will be implemented as @mbway showed as `hash(v1) == hash(v2)`, this may break some code, but comparing two vectors should be done by `v1.isclose(v2)` anyway!
2. changing `Vec2/Vec3.isclose()` to `isclose(v, *, rel_tol=1e-9, abs_tol=0)` with a relative tolerance like `math.isclose()`, but the default values may not match the `math.isclose()` values, to break as less code as possible.

**Comment by mozman** [comment]
@mbway can you check out branch "vec_eq" and test how big the impact of this change is for real world users?

**Comment by mbway** [comment]
The properties of equality and hashing are:
- `a == b  =>  hash(a) == hash(b)`
- `hash(a) != hash(b)  =>  a != b`

Note that there is *no requirement* for `hash(a) == hash(b)  =>  a == b`.

By defining equality by comparing the hashes, technically that obeys the requirements but does not mathematically may make sense because of hash collisions.

For example if the hash function hashed floating point numbers as `int(floor(x)) % (2**32)` (which is a poor hash function) then `1.1` and `1.9` would have the same hash (which is perfectly fine) but clearly have different values and should not be considered equal. `hash(a) == hash(b)` just indicates that `a` might equal `b`. It's used to quickly rule out things that are definitely not equal. It would be more difficult finding hash collisions in CPython's built in hash implementation but they will exist.


So either, you can keep `Vec.__eq__` as being defined as almost equal, so long as you ensure that the properties above hold. You could do this by rounding the values before hashing for example.

Or you could implement like so:
```
def __eq__(self, other):
    return isinstance(other, Vec2) and self.x == other.x and self.y == other.y
```
and keep `Vec.__hash__` as it is now.

I think by convention `__eq__` in other libraries usually means 'exactly equal' and having to use `.isclose` is more explicit, if less ergonomic. It's up to you but I think defining `__eq__` as 'exactly equal' makes more sense.

**Comment by mozman** [comment]
I didn't thought on hash collisions and `self.x == other.x ...` is okay for me.
