### ISSUE TITLE
Hatch drawing regression

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#466]
[hole.dxf.zip](https://github.com/mozman/ezdxf/files/6637537/hole.dxf.zip)
AutoCAD:
![image (44)](https://user-images.githubusercontent.com/4923501/121669748-8a611e80-caa4-11eb-8eb3-ee001c3a0555.png)

ezdxf as-of d9583d2ff484d14fe7be178ddc80380eb5de510a:
![image (45)](https://user-images.githubusercontent.com/4923501/121669768-92b95980-caa4-11eb-83e5-216d463f7257.png)
(some glitches but mostly OK)

ezdxf as-of 4422a7ab603ddb4dd9a289e6ab9be10e2bd1ed50 (current HEAD)
![image (46)](https://user-images.githubusercontent.com/4923501/121670099-fcd1fe80-caa4-11eb-9291-57a089582526.png)

**Comment by mbway** [comment]
I bisected and found the change was introduced in commit d2ef06597c4b9277039c699031dd49f23e5d13cb `ignore open edge path loops in HATCH entities #454`

**Comment by mozman** [comment]
This hatch edge loops issues getting annoying:

This is the missing path, because it is detected as an open loop:
![image](https://user-images.githubusercontent.com/4230966/121682402-585bb680-cabc-11eb-913d-d3744f6101ff.png)

First edge:
![image](https://user-images.githubusercontent.com/4230966/121682452-67daff80-cabc-11eb-919e-71550ffc8ac3.png)

Second edge:
![image](https://user-images.githubusercontent.com/4230966/121682505-75908500-cabc-11eb-8c15-523a58d0c105.png)

Second edge does not connect to the END of the first edge, which is the current implementation of connection detection.

third edge:
![image](https://user-images.githubusercontent.com/4230966/121682656-a2449c80-cabc-11eb-8acd-21268ca27b2c.png)

The next escalation would be to randomly shuffle all of the paths.

First, I'll try a solution without the shuffled paths" scenario.

**Comment by mozman** [comment]
Fixed until a random shuffled edge path appears:
![image](https://user-images.githubusercontent.com/4230966/121693649-9f9c7400-cac9-11eb-87fa-c0ccb247e17a.png)

**Comment by mbway** [comment]
thanks for your help. That works great :)
