### ISSUE TITLE
Question: why some inserts (or attribs) are invisible?

### ISSUE THREAD

**Issue by konradmalik** [mozman/ezdxf#504]
Hi,
question from me as I cannot understand why some of the inserts are not drawn on PNG.
Things to know:
- I use an external DXF (I did not create it) and sorry but I also cannot share it
- I use Matplotlib backed to generate PNG

What I'm doing:
- I'm loading a drawing version 2000 and generating a PNG file from it
- Thing is, when I do not explode the inserts, some items are not visible on the generated PNG, they are not rendered.
- However, when I do explode those inserts, those initially hidden things appear on the PNG, they are clearly rendered.

Question:
- How does ezdxf, matplotlib or whatever, determine if the item should be rendered or not 
- why is this info lost when exploding the insert?

What I think I know:
- I know that during `explode`, Attribs are converted to Text. I guess this is the possible "data loss" point? But I still don't know how is this info stored in the first place.
- I checked a bunch of attributes like "invisible", "is_invisible", "transparency", even colors for some weird reason. Nothing here indicates that the element should be invisible (invisible is 0, is_invisible (for attribs) is False, transparency is 0)

Keep in mind that my use-case is different. I need to do some logic based on those invisible elements but I don't know how to identify them.

**Comment by mbway** [comment]
> How does ezdxf, matplotlib or whatever, determine if the item should be rendered or not

It's ezdxf making the decisions, matplotlib is simply used as a graphics API to produce the image. The visibility of each entity is determined by several properties in the dxf file such as the layer visibility  (which is controlled by two properties, visibility and 'frozen'), but there are cases like inserts where visibility behaves strangely (such as visibility of the insert doesn't affect child entities etc). ezdxf aims to mimic this behaviour. 
This logic is implemented in `ezdxf.addons.drawing.properties` (see `Properties.is_visible`). There are some options for the command line utility you can use to draw everything: `ezdxf draw --all-layers-visible <path>` or `ezdxf draw --all-entities-visible <path>` or you can create a custom frontend and selectively alter the visibility of entities using `Frontend.overwrite_properties`:
```python
class MyFrontend(Frontend):
    def override_properties(self, entity: DXFGraphic, properties: Properties) -> None:
        properties.is_visible = True  # or something more complex
```

> why is this info lost when exploding the insert?

I'm not sure, but it sounds like a consequence of the complex visibility logic I described above. Once you explode an insert, the rules change because the child entities may be put on different layers.


It could also potentially be a bug. You could try either using a debugger or logging to see what is going on. The logic in the frontend and backend classes are quite easy to follow

**Comment by mozman** [comment]
If you have access to a CAD application, do the INSERT explosion in the CAD application an compare the result with ezdxf. If the results are different, it could be a bug in ezdxf. Or you can upload the (zipped) DXF file and script to generate the PNG and I can do the comparison.

**Comment by konradmalik** [comment]
soo, some observations on my end. I solved the issue but not sure if this is a bug or not:
- I create a RenderContext using my drawing and called `resolve_all` on the entities in question
- turns out that Attribs have `is_visible=True` while the parent Insert has `is_visible=False`
- I called both (probably both are not needed) `e.is_invisible = True` and `e.dxf.invisible = 1` on all Attribs of the hidden Insert
- This whay, after explode, my Text entities that were created from Attribs are properly resolvable as invisible (I use the same approach with RenderContext here, but probably it is sufficient to check `e.dxf.invisible == 1`

I really wish I could help by sending the diagram but I really can't due to company/privacy.
