### ISSUE TITLE
Modifying MTEXT in existing DXF does not always preserve text alignment

### ISSUE THREAD

**Issue by ornithophile** [mozman/ezdxf#507]
Hello, I am using this library in production and noticing that when I have a DXF with MTEXT entities aligned as middle center etc, they are saved as top left after the drawing is modified. When I have some time I can try to come up with a minimal example.

**Comment by mozman** [comment]
Please provide an example, because my testing does not show any errors for DXF versions R2000-R2018:

Source DXF:
![image](https://user-images.githubusercontent.com/4230966/126854906-531a7df0-5a3c-48e4-b8c3-f277668c1c23.png)

Added line "add" to MTEXT entity and saved by ezdxf:
![image](https://user-images.githubusercontent.com/4230966/126854922-e95011fb-aa26-431e-845d-1ada7c4266fb.png)

**Comment by ornithophile** [comment]
Going to close this until I can stumble into an example again. We were using a 2018 DXF with many pieces of MTEXT aligned middle center. I have a script that opens the DXF, replaces a bunch of custom variable values and sets attributes in title blocks. After running, the MTEXT would change to top left and the MTEXT shifted appropriately (insertion point was the same).
