### ISSUE TITLE
saving issue

### ISSUE THREAD

**Issue by zohw** [mozman/ezdxf#529]
When I read a dxf file by ezdxf and save it again without any other modifications, some information may loss during this process. For example, some linetypes do not display as expected in the saved file. Do you have any solutions?

**Comment by mozman** [comment]
I need more information, see also template for creating a bug report:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Information and data needed to reproduce the error:
1. A *simplified* Python script which triggers the error.
2. Information about the *ezdxf* version and the OS.
3. If a 3rd party DXF file causes the error, add a *simplified* and *zipped* 
   DXF file which still triggers the error.

**Confidential Data**
If you have sensitive files that you can't disclose, try to remove everything 
sensitive from an existing file or create a brand new one which still triggers 
the error. Alternatively, you can send the zipped files to confidential@mozman.at, 
this data is only saved locally (no cloud upload of any kind) and the files are 
deleted after the error has been fixed.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by zohw** [comment]
Describe the bug
When I read a dxf file by ezdxf and save it again without any other modifications,  the saved file can't be opened successfully or the linetype of lines can't be discplay correctly.

To Reproduce
```
#ezdxf version 0.16.6
#os Windows 10 
#dxf file link: https://drive.google.com/file/d/1Z6pemA3X2WGuBb-iqR_QeeptG6EiEi6P/view?usp=sharing
import ezdxf
doc = ezdxf.readfile("./x3.ezdxf")
doc.saveas("./check.dxf")
```
Expected behavior: the saved file can be opened and the linetype of the line is displayed correctly.

**Comment by zohw** [comment]
Today I can't reproduce problem again, sorry for bothering.  I decide to close this issue for now. 
Here I would like to take the opportunity to express our gratitude for your excellent work. Thanks...
