### ISSUE TITLE
Color value is wrong?

### ISSUE THREAD

**Issue by Febfire** [mozman/ezdxf#53]
I got color of dxf by "e.dxf.color".But i found it just a single value and even being 256?
What's mean?
I don't understand,is it the color of layer?

**Comment by mozman** [comment]
The color value represents an *ACI* (AutoCAD Color Index). AutoCAD and every other CAD application provides a  default color table, but *pen table* would be the more correct term. Each ACI entry defines the color value, the line  weight and some other attributes to use for the pen. This pen table can be edited by the user or loaded from an  *.ctb* file.

DXF R12 and prior are not good in preserving the layout of a drawing, because of the lack of a standard color table defined by the DXF reference and missing DXF structures to define these color tables in the DXF file. So if a CAD user redefined an ACI and do not provide a .ctb file, you have no ability to determine which color or lineweight was used. This is better in later DXF versions by providing additional DXF attributes like *lineweight*, *true_color* and *transparency*.

BUT ACI is not at bad at all, by using ACI you can define different output styles for different purposes (e.g. color or B&W ouput) without editing the content.

special color values:
BYBLOCK = 0
BYLAYER = 256
BYOBJECT = 257 (DXF R13 and later)
