### ISSUE TITLE
Injecting uuids during SVG conversion

### ISSUE THREAD

**Issue by bdaniere** [mozman/ezdxf#549]
Hello,
I'm using the DXF to SVG conversion but entities uuid are lost in the process.
One of the problem is sub-geometries. Mathplotlib doesn't support groups (<g>) so we can't associate one uuid to many geometries in the SVG.
Instead of generating a new uuid for each entity, I plan to keep the original uuid (if there is one) and append _1, _2, ... to each sub-geometry so the SVG keeps unique ids.

I can open a PR but your advice may be useful.

**Comment by mbway** [comment]
do you mean like when a lypolyline is broken down into several line segments and curves? in which case I think appending `_1`, `_2` etc is a good idea. I'm not sure what question you're asking, is this approach causing problems?

I think you will have problems with INSERT entities. Especially since you can nest INSERTs inside of INSERTs and the 'virtual entities' inside them have no handle in the dxf. I don't know how best you could identify those. Maybe those entities have handles in the block where they originate but I don't know

**Comment by mozman** [comment]
- All (real) DXF entities stored in a DXF document have a handle (hex-string), accessible by `DXFEntity.dxf.handle`.
- All virtual entities, which are temporarily created entities by copying the original entity or entities created by instantiating the entity class without using a factory method, have no handle until they are bound to a DXF document.
- The property `DXFEntity.uuid` returns an UUID for each DXF entity, even virtual entities. This UUID is created at runtime at the first access of the `uuid` property, it is created by `uuid.uuid4()`. This UUID is not stored in the DXF file and also would not work for virtual entities, because they are not stored in the DXF file.
- The content entities in block references (INSERT) are always virtual entities. They are the result of copying the original BLOCK entities and transforming them to their new position, orientation and size according the parameters of the INSERT entity. These copies do not carry a reference to the source entity in the BLOCK definition.
