### ISSUE TITLE
Manylinux2010 wheels required/needed?

### ISSUE THREAD

**Issue by mozman** [mozman/ezdxf#587]
@mbway @odidev 

The new workflow for creating `manylinux2014_aarch64` wheels added by @odidev seems more future proof than the current workflow for creating `manylinux2010_x86_64` wheels.

The workflow to build `manylinux2014_x86_64` wheels is already working. 

My question to linux users: **Are `manylinux2010_x86_64` wheels still useful/needed in practice?**

Adding support for manylinux2010_x86_64 wheels by the new workflow isn't a big deal, but every piece of code has to be maintained.

**Comment by mbway** [comment]
I'm seeing that packages like [numpy](https://pypi.org/project/numpy/#files) and [scikit-learn](https://pypi.org/project/scikit-learn/#files) still have manylinux2010 packages. Based on [this page](https://github.com/pypa/manylinux) that version of manylinux does correspond to modern distributions (eg Ubuntu 20.04) and python versions 3.7 and 3.8.

So manylinux2010 isn't massively outdated, but manylinux2014 also seems to cover the same versions and 3.9. The most recent version is the manylinux_x_y spec which goes by libc version instead of a year.
[this package](https://pypi.org/project/orjson/#files) provides only manylinux_x_y packages

**Comment by mozman** [comment]
Thank you for the feedback. I will follow `numpy`, which switched for Python 3.10 to `manylinux2014` and uses `manylinux2010` for older Python versions for the x86 platform. Providing wheels for `manylinux2010_x86_64` and `manylinux2014_x86_64` for the same Python version seems not very useful.

A look at the `numpy` repository leads to one more question:
Why not using https://github.com/pypa/cibuildwheel? Which seems to support everything.
