### ISSUE TITLE
Text drawing regressions

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#620]
ezdxf v0.16 rendered text more accurately in many cases, although v0.17.2 does handle multiple column placement better.
I checked out the two versions of ezdxf and ran:
```
cd examples_dxf
ezdxf draw text.dxf
```
Here are the results:
v0.16
![out_v16](https://user-images.githubusercontent.com/4923501/150528393-8b5a9bc2-3ba1-4a94-a53a-f23172487b0e.png)

v0.17.2
![out_v17](https://user-images.githubusercontent.com/4923501/150528424-b28fd4ad-8c96-4bd1-af8c-6f433cbf9468.png)

For comparison, here is what the file looks like in autocad:
![text](https://user-images.githubusercontent.com/4923501/150528934-994b3b1e-e17e-4b11-a18e-9d8b7801727d.png)

differences highlighted. Question marks indicate places where the difference may not be necessarily worse
![differences](https://user-images.githubusercontent.com/4923501/150528711-e2542920-5cd5-4f9f-a32f-dd4ae1ed794d.png)

**Comment by mbway** [comment]
I found that the 'Standard style' is supposed to be bold, so the headings on the right and the 'Standard Style' text now being bold is correct. Also replacing `draw_complex_mtext` with `draw_simple_mtext` is more accurate in a lot of cases but doesn't support caret encoding
v0.17.2 with draw_simple_mtext
![text](https://user-images.githubusercontent.com/4923501/150545468-9c6743b6-5455-4f98-98d9-ea36e1196074.png)

**Comment by mozman** [comment]
Many issues are caused by text wrapping. `Matplotlib` does text rendering different than AutoCAD or BricsCAD. The yellow outlines show the `Matplotlib` rendering and the white text is rendered by TrueView (AutoCAD):

![image](https://user-images.githubusercontent.com/4230966/150558711-b86245b5-577e-4e1a-a713-aa09ea2bcb01.png)

The MTEXT entity does not store the text wrap locations, only the column width. By using `Matplotlib` to calculate the text width, the text wrapping will never be exact the same as in AutoCAD or BricsCAD.

**Comment by mozman** [comment]
These are all very special cases of line wrapping or handling of "space" characters in context of line-wrapping. 

I won't fix anything of that. Time is too precious to waste it for rare edge cases.

**Comment by mbway** [comment]
so long as accurate placement is still available by creating a custom frontend and overriding `draw_complex_mtext` I'm happy. I find accurate placement and one `Text` entity per line much more important than accurate styling.
