### ISSUE TITLE
3dface crash

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#621]
using `exdxf draw examples_dxf/3dface.dxf`
v0.16:
```
Not a DXF file or a generic I/O error: 3dface.dxf
```
v0.17.2
```
Traceback (most recent call last):
  File "bin/ezdxf", line 33, in <module>
    sys.exit(load_entry_point('ezdxf', 'console_scripts', 'ezdxf')())
  File "ezdxf/src/ezdxf/__main__.py", line 98, in main
    run(args)
  File "ezdxf/src/ezdxf/commands.py", line 377, in run
    frontend.draw_layout(layout, finalize=True)
  File "ezdxf/src/ezdxf/addons/drawing/frontend.py", line 181, in draw_layout
    self.draw_entities(
  File "ezdxf/src/ezdxf/addons/drawing/frontend.py", line 212, in draw_entities
    self.draw_entity(entity, properties)
  File "ezdxf/src/ezdxf/addons/drawing/frontend.py", line 233, in draw_entity
    draw_method(entity, properties)
  File "ezdxf/src/ezdxf/addons/drawing/frontend.py", line 379, in draw_solid_entity
    assert len(points) - 1 == len(edge_visibility)
```

**Comment by mozman** [comment]
The rendering of the two 3DFACE entities are different to AutoCAD and can not work in `ezdxf`, because `ezdxf` ignores the 4th vertex if equal to the 3rd vertex (triangle). therefore the 3rd edge (visible) is not 3rd->4th vertex (point), its 3rd->1st vertex (line - visible):

![image](https://user-images.githubusercontent.com/4230966/150624054-61e633a0-95ce-4ae1-97e2-c54dc50ed396.png)

I consider such special cases as misuse of the 3DFACE entity - a face is a face and not a line and I don't care about the interpretation of AutoCAD!

**Comment by mbway** [comment]
for context, I think I have seen instances where 3DFace was indeed used to draw a 'line' in that a floorplan used 3DFACE to represent a window but when viewed in 2D the sides of the window were 0-length and the top and bottom were identical.

I had a quick look and I don't think any version of ezdxf handled those two highlighted cases properly so this isn't a regression.

**Comment by mozman** [comment]
A support for this "feature" would also break the current behavior of `ezdxf`.

I won't add support for such "features" in the future because the DXF reference does not document such special cases and I have neither the time nor the interest to make `ezdxf` 100% AutoCAD compatible. I get more and more annoyed by problems like this - they suck the fun out of this project.
