### ISSUE TITLE
Creating Dimensions

### ISSUE THREAD

**Issue by itrevex** [mozman/ezdxf#67]
According to author of ezdxf and dxfwrite, all features of dxfwrite are part of ezdxf. There is one feature in dxfwrite that seems to be missing in ezdxf and that is the dimension. 

I am not a super programmer to know how I can mix features in dxfwrite with ezdxf but adding dimensioning to ezdxf will make the package superb.

Thanks for all the good work.

**Comment by mozman** [comment]
The dxfwrite dimensions are available as addons `ezdxf.addons.dimlines`, for usage see this [example](https://github.com/mozman/ezdxf/blob/master/examples/addons/using_dimlines_addons.py).

This addon is not documented. I don't want to encourage the usage of this fake dimensions because real DIMENSION support is coming to ezdxf.
