### ISSUE TITLE
ezdxf.lldxf.const.DXFAttributeError: Invalid DXF attribute "name" for entity DICTIONARY

### ISSUE THREAD

**Issue by PinkMushroom** [mozman/ezdxf#687]
unfortunately i can't upload the file that generates this error.  I looked in the file and there are a LOT of DICTIONARY, so without a line number i'm stuck as to whether or not it's a particular instance of DICTIONARY, or all of them.

However if i could identify the line number where it's happening i could upload a snippet.

So part of this issue is, would it be possible to print the line number location in the DXF where the error occurred ?

**Comment by mozman** [comment]
Maybe you can't send  the DXF file to confidential@mozman.at, otherwise it is not possible to help.

It could be a very specific use case of a standard AutoCAD DICTIONARY, but this is very unlikely as `ezdxf` has processed a lot of DXF files over the years, also very strange ones. Or it's just an invalid DXF file.

**Comment by PinkMushroom** [comment]
The funny thing is i was testing some code using an autocad generated file and had no problem.  This is a dxf file generated by a different CAD program.  I would not be surprised at all if it is generating a broken file (although autocad can read it). 

I realized after i opened the issue, of course, that i can simply keep trimming the file down until i have a minimum error example and then it will be no problem to send you the file.  Thank you for ezdxf !

**Comment by mozman** [comment]
The first thing you could try is to delete the content of the `ENTITIES` section with a text editor:
```text
0
SECTION
2
HEADER
...
0
ENDSEC
... more seections CLASSES, TABLES, BLOCKS
0
SECTION
2
ENTITIES
... delete anything between these two tags
0
ENDSEC
0
SECTION
2
OBJECTS
... this is the important part to debug
0
ENDSEC
0
EOF
```

To be clear the `ENTITIES` section should look like this:

```text
...
0
ENDSEC
0
SECTION
2
ENTITIES
0
ENDSEC
0
SECTION
2
OBJECTS
...
```

The modelspace is empty if you open the file with AutoCAD.

The section names `ENTITIES` and `OBJECTS` should be unique search targets.

I want to fix this issue, because if AutoCAD can open the file it's per definition DXF compatible. I also don't like it when AutoCAD is more error-tolerant than `ezdxf` because  AutoCAD is very picky.

**Comment by mozman** [comment]
The sample file you sent without the ENTITIES section didn't throw an exception, which is strange since the DICTIONARY entity can only exist in the OBJECTS section.

Did you try the `ezdxf.recover` module to load the DXF file, which can fix known errors at the loading stage?

**Comment by mozman** [comment]
I extended the `try/except` clause in 0.18 to catch this kind of errors

**Comment by mozman** [comment]
The `DIMSTYLE` entity expects a handle to a `STYLE` table entry and gets a handle to a `DICTIONARY` entity, so I would say: yes,  there is a problem in the DXF file.

**Comment by PinkMushroom** [comment]
Sorry, i hadn't read your email yet.  Just to verify I removed the first DIMSTYLE entry and then things got interesting.  ezdxf can now read the file without a problem.
Librecad could read the file successfully, but autocad could NOT. it didn't throw and error but it wouldn't read the file.
Thank you for your help!
