### ISSUE TITLE
Does EZDXF have a way to implement the AutoCAD 'explode' function?

### ISSUE THREAD

**Issue by shine-flower** [mozman/ezdxf#743]
Implement similar functions #742 
> After the above operation is completed, the filling is realized, which is a block in DXF, and it can not recognize the concept of block in the laser marking machine. I'll go into AutoCAD and run the 'explode' command, and the laser marker will identify the filled line.Does EZDXF have a way to implement the AutoCAD 'explode' function?
Before use 'explode' command
![image](https://user-images.githubusercontent.com/105044629/190960476-9bc55c02-4816-4478-b583-de4d099a2ad7.png)
After use 'explode' command
![image](https://user-images.githubusercontent.com/105044629/190960314-cf73f038-bf05-4a08-ade5-501ab1d4f58f.png)

**Comment by mozman** [comment]
The generated entity is called `HATCH` and it's not a `BLOCK` reference a.k.a. `INSERT` entity.

There is no general ` EXPLODE` command implemented in `ezdxf`, but some entities can be broken down into DXF primitives like the `INSERT` entity, the `POLYLINE` entity and the `HATCH` entity. But exploding the `HATCH` entity does not render the pattern lines because the current hatching algorithm has some flaws and I don't know a better one.

The rendering of the `HATCH` pattern as `LINE` primitives is possible by the `ezdxf.hatching` module but the result may not be 100% correct. I added this function to the example script [text_string_to_hatch.py](https://github.com/mozman/ezdxf/blob/master/examples/addons/text_string_to_hatch.py):

```python
from ezdxf.gfxattribs import GfxAttribs
from ezdxf.render import hatching

...

def render_hatch_entities():
    doc = ezdxf.new()
    msp = doc.modelspace()

    hatches = text2path.make_hatches_from_str(SAMPLE_STRING, font=FONT, size=4)
    offset = (0, 0.05)  # (x, y) offset in drawing units
    # The hatching algorithm has some issues when pattern lines are coincident
    # to HATCH boundary lines, shifting the origin of the pattern slightly by an
    # arbitrary small amount may prevent such problems:
    origin = (0.00142387564, 0.0067462384)
    MY_PATTERN = [[0.0, origin, offset, []]]

    for hatch in hatches:
        hatch.set_pattern_fill(
            name="MY_PATTERN",
            color=1,
            style=0,  # 0 = normal; 1 = outer; 2 = ignore
            pattern_type=2,  # 0 = user-defined; 1 = predefined; 2 = custom
            # I have no idea what the difference between a user-defined pattern
            # type and a custom pattern type is, both values work for this example.
            definition=MY_PATTERN,
        )
        # Adding LINE entities to the modelspace instead of HATCH entities:
        attribs = GfxAttribs(color=ezdxf.colors.RED)
        for start, end in hatching.hatch_entity(hatch):
            msp.add_line(start, end, dxfattribs=attribs)

    zoom.extents(msp)
    doc.saveas(CWD / "text2lines.dxf")

```

**Comment by shine-flower** [comment]
> Thank you very much. It worked out exactly as I wanted.
