### ISSUE TITLE
ACAD_PROXY_ENTITY creates extra hatch with ezdxf view

### ISSUE THREAD

**Issue by miiarantala** [mozman/ezdxf#906]
**Describe the bug**
Extra hatch is rendered for proxy graphics. 
The proxy graphics are originally AutoCAD Plant3D pipelines that are drawn with parallel lines.

**To Reproduce**
`ezdxf view test.dxf`
version: ezdxf 1.1.0b4
Test DXF file here: [test.zip](https://github.com/mozman/ezdxf/files/11915635/test.zip)

**Expected behavior**
DXF would be rendered without the hatches.

**Screenshots**
Ezdxf view:
![image](https://github.com/mozman/ezdxf/assets/106882671/f3ae1d6d-79ed-43ac-b919-325d26cf5a11)
Autodesk TrueView:
![image](https://github.com/mozman/ezdxf/assets/106882671/c561d90e-50c4-4797-9966-be61811557f3)

**Comment by mozman** [comment]
The filling is now ignored for polylines even when the fill flag is set and the linetype parsing is fixed:

![image](https://github.com/mozman/ezdxf/assets/4230966/a8d328ec-caa3-4ddb-a630-34ce2415e8ae)

The linetyle "SolidFuels" is drawn as solid line and I have no idea why but the error is not in the `ProxyGraphic` class, most likely somewhere in the `drawing` add-on:

![image](https://github.com/mozman/ezdxf/assets/4230966/e6e3e1e7-15b6-4344-99e7-69284140b3be)

The "SolidFuels" linetype in BricsCAD, which is a very wide dot pattern:
![image](https://github.com/mozman/ezdxf/assets/4230966/309788b0-8b1c-4e99-a530-41a8d1976457)

I found a method to get BricsCAD's proxy graphic representation for any DXF entity type by using a MLEADER with block content, for which BricsCAD always generates a proxy graphic since the block can contain anything.

**Comment by mozman** [comment]
I added a feature to explode ACAD_PROXY_ENTITIES into proxy graphic. BricsCAD has no problem to open the file but Autodesk Trueview 2023 displays the error message "Invalid or incomplete DXF input -- drawing discarded", which is not very helpful.

Can someone open the file `906_exploded.dxf` by the RECOVER command of AutoCAD and post the diagnosis here? 

The RECOVER command of BricsCAD can not find any errors!

[906_exploded.zip](https://github.com/mozman/ezdxf/files/11929843/906_exploded.zip)
